In [1]:
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
import json

Import data:

In [2]:
smoke_csv = "./10km_grid/smokePM2pt5_predictions_daily_10km_20060101-20201231.csv"
smoke = pd.read_csv(smoke_csv)
smoke['date'] = pd.to_datetime(smoke['date'], format="%Y%m%d")

In [17]:
mobility_csv = "california_202008_202009.csv"
mobility_data = pd.read_csv(mobility_csv)

In [18]:
mobility_data.head()

,AFTERNOON_TEA_DEVICE_HOME_AREAS,AREA,AREA_TYPE,BREAKFAST_DEVICE_HOME_AREAS,DATE_RANGE_END,DATE_RANGE_START,DAY_COUNTS,DEVICE_COUNTS,DEVICE_DAYTIME_AREAS,DEVICE_HOME_AREAS,...,STOPS_BY_DAY,STOPS_BY_EACH_HOUR,STOP_COUNTS,TOP_SAME_DAY_BRAND,TOP_SAME_MONTH_BRAND,WEEKDAY_DEVICE_HOME_AREAS,WEEKEND_DEVICE_HOME_AREAS,WORK_BEHAVIOR_DEVICE_HOME_AREAS,WORK_HOURS_DEVICE_HOME_AREAS,YEAR
0,"{""060650432181"":791,""060650432462"":51,""0606504...",60650432181,Census Block Group,"{""060650432181"":760,""060650432171"":123,""060650...",2020-09-01 00:00:00,2020-08-01 00:00:00,"{""Monday"":5,""Tuesday"":4,""Wednesday"":4,""Thursda...",6486,"{""060650432181"":904,""060650432171"":226,""060650...","{""060650432181"":986,""060650432171"":236,""060650...",...,"[1377,1531,1377,1469,1490,1634,1582,1716,1284,...","[30,10,0,10,0,10,0,10,102,51,61,41,164,92,51,9...",48651,"{""Kimco Realty"":9,""Target"":7,""Realty Income"":6...","{""Target"":29,""Walmart"":28,""Costco"":27,""Kimco R...","{""060650432181"":966,""060650432171"":185,""060650...","{""060650432181"":935,""060650432171"":185,""060650...","{""060650432181"":719,""060650432171"":30,""0606504...","{""060650432181"":873,""060650432171"":143,""060650...",2020
1,"{""060930007011"":411,""060930007013"":154,""060930...",60930007011,Census Block Group,"{""060930007011"":431,""060930007022"":185,""060930...",2020-09-01 00:00:00,2020-08-01 00:00:00,"{""Monday"":5,""Tuesday"":4,""Wednesday"":4,""Thursda...",6475,"{""060930007022"":606,""060930007011"":534,""060930...","{""060930007011"":503,""060930007022"":431,""060930...",...,"[2210,1531,1665,2251,1911,2425,2271,2025,1675,...","[20,20,41,51,71,30,41,71,113,154,92,205,133,11...",60719,"{""Walmart"":17,""Ace Hardware"":4,""Tractor Supply...","{""Walmart"":55,""Costco"":17,""Home Depot"":15,""Sta...","{""060930007011"":493,""060930007022"":328,""060930...","{""060930007011"":452,""060930007022"":236,""060930...","{""060930007011"":359,""060930007022"":30,""0609300...","{""060930007011"":472,""060930007022"":277,""060930...",2020
2,"{""060411211001"":472,""060411212001"":205,""060411...",60411211001,Census Block Group,"{""060411211001"":462,""060411212001"":164,""060411...",2020-09-01 00:00:00,2020-08-01 00:00:00,"{""Monday"":5,""Tuesday"":4,""Wednesday"":4,""Thursda...",35761,"{""060411211001"":925,""060411212002"":585,""060411...","{""060411211001"":668,""060411212002"":400,""060411...",...,"[3967,3248,4070,3936,4337,3947,4101,3895,3474,...","[41,10,0,0,10,0,41,82,20,82,256,370,534,483,49...",122178,"{""Mall"":40,""Macerich"":12,""Starbucks"":9,""Target...","{""Mall"":51,""Target"":30,""Starbucks"":30,""Costco""...","{""060411211001"":647,""060411212002"":318,""060411...","{""060411211001"":534,""060411212001"":226,""060411...","{""060411211001"":339,""060411082001"":20,""0604111...","{""060411211001"":565,""060411212003"":256,""060411...",2020
3,"{""060374327003"":195,""060374332004"":164,""060374...",60374327003,Census Block Group,"{""060374327003"":195,""060374327001"":154,""060374...",2020-09-01 00:00:00,2020-08-01 00:00:00,"{""Monday"":5,""Tuesday"":4,""Wednesday"":4,""Thursda...",33828,"{""060374327002"":390,""060374327003"":349,""060374...","{""060374324021"":359,""060374324023"":349,""060374...",...,"[2867,2405,2939,2723,2271,2909,2960,2734,2374,...","[0,10,0,0,10,0,30,123,113,174,215,226,277,287,...",82398,"{""Walmart"":7,""Sam's Club"":6,""Home Depot"":5,""St...","{""Walmart"":40,""Home Depot"":24,""Starbucks"":23,""...","{""060374327003"":318,""060374326012"":318,""060374...","{""060374324021"":277,""060374327003"":256,""060374...","{""060374327003"":215,""060710020101"":20,""0603731...","{""060374327003"":267,""060374326012"":256,""060374...",2020
4,"{""060014426021"":678,""060014417002"":41,""0600143...",60014426021,Census Block Group,"{""060014426021"":729,""060014418001"":71,""0600144...",2020-09-01 00:00:00,2020-08-01 00:00:00,"{""Monday"":5,""Tuesday"":4,""Wednesday"":4,""Thursda...",4831,"{""060014426021"":770,""060014418001"":195,""060014...","{""060014426021"":955,""060014418001"":195,""060014...",...,"[1315,1202,1356,1233,1140,1223,1171,1305,1110,...","[20,0,0,10,0,0,0,10,30,41,61,71,143,82,61,82,1...",40016,"{""Realty Income"":16,""Kimco Realty"":14,""Costco""...","{""Realty Income"":38,""Kimco Realty"":36,""Costco""...","{""060014426021"":935,""060014418001"":133,""060014...","{""060014426021"":904,""060014418001"":102,""060014...","{""060014426021"":760,""060014418001"":20,""0600143...","{""060014426021"":873,""060014417002"":82,""0600144...",2020

In [21]:
mobility_data['STOPS_LIST'] = mobility_data['STOPS_BY_DAY'].apply(json.loads)
mobility = mobility_data[['AREA', 'STOPS_LIST']].explode('STOPS_LIST')
mobility['Day'] = mobility.groupby('AREA').cumcount() + 1
mobility['Stops'] = mobility['STOPS_LIST'].astype(int)
mobility.head()

          AREA STOPS_LIST  Day  Stops
0  60650432181       1377    1   1377
0  60650432181       1531    2   1531
0  60650432181       1377    3   1377
0  60650432181       1469    4   1469
0  60650432181       1490    5   1490

In [24]:
stops_mean = np.mean(mobility['Stops'])
stops_sd = np.std(mobility['Stops'])
mobility['Stops_standardized'] = (mobility['Stops'] - stops_mean) / stops_sd
mobility.head()

,AREA,STOPS_LIST,Day,Stops,mean_x,std_x,mean_y,std_y,Stops_standardized
0,60650432181,1377,1,1377,1472.327869,223.673327,1472.327869,223.673327,-0.281745
1,60650432181,1531,2,1531,1472.327869,223.673327,1472.327869,223.673327,-0.231179
2,60650432181,1377,3,1377,1472.327869,223.673327,1472.327869,223.673327,-0.281745
3,60650432181,1469,4,1469,1472.327869,223.673327,1472.327869,223.673327,-0.251537
4,60650432181,1490,5,1490,1472.327869,223.673327,1472.327869,223.673327,-0.244641